python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
pip install mpld3
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
pip install plotly
exit
python scripts/synthetic_data_generation/main/transform_test_data_set.py
exit
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
print('---')
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
clear
clear
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
python scripts/synthetic_data_generation/main/transform_test_data_set.py
git add .
exit
