version: '3.8'
services:
  api:
    container_name: api
    build:
      context: './'
      dockerfile: './docker/api/Dockerfile'
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
        USER: ${USER:-root}

    ports:
      - "5000:5000"
    volumes:
      - ./:/home/ccs4dt
    networks:
      - ccs4dt
    environment:
      - FLASK_APP
      - FLASK_ENV
      - FLASK_HOST
      - FLASK_PORT
      - FLASK_DEBUG

  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./storage/influx_db:/var/lib/influxdb2 # Location where influxDB stores data
      - ./config:/etc/influxdb2
    networks:
      - ccs4dt
    environment:
      - DOCKER_INFLUXDB_INIT_MODE
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
networks:
  ccs4dt: