name: Generate documenation

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate documentation
      run: |
        bash scripts/docs/generate.sh

    - name: Commit documentation
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Updated documentation'
        add: 'docs/*'
